### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by cowboysdude** [fewieden/MMM-voice#20]
Platform (Hardware/OS):
Unbuntu 16

Node version:
8.9.4
MagicMirror version:
2.2.2
Module version:
Lastest Master
Description of the issue:
when starting it intializes then goes right to ERROR
When run in debug: true it says undefined.
I ran the command line and my mic is 0.....

Not sure what's undefined but I've tried the mic at 0 and 1......still get ERROR

**Comment by cowboysdude** [comment]
Fixed it.  Thanks

**Comment by fewieden** [comment]
Could you pls report for other users, what caused the issue und how you fixed it?

**Comment by cowboysdude** [comment]
Don’t run them in the MagicMirror directory. Just open a new terminal window and run them
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
and
sudo ldconfig
the 2nd will need your password
and this will verify your microphone number for your config
cat /proc/asound/cards]]

;)

**Comment by KriyenKP** [comment]
Still having this issue. Says "Error" on Mirror. But I set the right mic on config. Using a USB PnP Sound Device and it works fine with AlexaPi. Think there's a clash maybe??

**Comment by fewieden** [comment]
@KriyenKP i have no experience with alexapi

But you could check the error log for more details

**Comment by mikeb8319** [comment]
I'm getting the dreaded "WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration." Everytime I delete the MMM-Voice, the error message goes away. Below is how I copied it on my scrip. 
                 {
                       module: "MMM-voice",
                       position: "bottom_bar",
                       config: {
                       microphone: 1,
                       ...
                }
                },

**Comment by fewieden** [comment]
remove the `...`

**Comment by mikeb8319** [comment]
Not sure how I missed that. Thanks, homie.

**Comment by adbeem** [comment]
hi fewieden, i tried the two commands:
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
sudo ldconfig
but nothing showed up. i check the file directory and i cant seem to find any ldconfig file (also in hidden mode). it is missing somewhere?

**Comment by adbeem** [comment]
It starts from initializing then ready choose a mode and immediately goes to ERROR, i checked the error.log it shows 1 1 1 1 1 1 ...
